version: '3'

services:
  mongo-db:
    image: mongo
    container_name: deliver-mongo-db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: Administrator
      MONGO_INITDB_ROOT_PASSWORD: manage
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - deliver_data:/data/db

  mongo-seed:
    build:
      context: ./data
      no_cache: true
    depends_on:
      - mongo-db

  mongo-express:
    image: mongo-express
    container_name: deliver-mongo-express
    depends_on:
      - mongo-db
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo-db
      ME_CONFIG_MONGODB_ADMINUSERNAME: Administrator
      ME_CONFIG_MONGODB_ADMINPASSWORD: manage
      ME_CONFIG_BASICAUTH_USERNAME: Administrator
      ME_CONFIG_BASICAUTH_PASSWORD: manage
    ports:
      - 8081:8081

  deliver-api:
    build:
      context: .
    image: jiridj/deliver-api
    container_name: deliver-api
    restart: unless-stopped
    environment:
      - NODE_ENV=development
    ports:
      - 3333:3333
    depends_on:
      - mongo-db

volumes:
  deliver_data:
